# Generated by Django 4.2.3 on 2025-07-01 07:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userID',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='userID')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyNotesUser',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='MoneyNotesUser_user_id', serialize=False, to='main.userid')),
                ('first_name', models.CharField(max_length=50, verbose_name='firstName')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='lastName')),
                ('user_name', models.CharField(max_length=25, unique=True, verbose_name='userName')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('first_login', models.DateTimeField(default=datetime.datetime(2025, 7, 1, 7, 57, 18, 838421, tzinfo=datetime.timezone.utc), verbose_name='firstLogin')),
                ('last_login', models.DateTimeField(default=datetime.datetime(2025, 7, 1, 7, 57, 18, 838421, tzinfo=datetime.timezone.utc), verbose_name='lastLogin')),
            ],
            options={
                'ordering': ['first_login'],
            },
        ),
    ]
