# Generated by Django 4.2.3 on 2025-07-01 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_moneynotesuser_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneynotesuser',
            name='first_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 8, 9, 54, 353522, tzinfo=datetime.timezone.utc), verbose_name='firstLogin'),
        ),
        migrations.AlterField(
            model_name='moneynotesuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 8, 9, 54, 353522, tzinfo=datetime.timezone.utc), verbose_name='lastLogin'),
        ),
    ]
