# Generated by Django 4.2.3 on 2025-07-01 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_moneynotesuser_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneynotesuser',
            name='first_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 9, 41, 52, 56343, tzinfo=datetime.timezone.utc), verbose_name='firstLogin'),
        ),
        migrations.AlterField(
            model_name='moneynotesuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 9, 41, 52, 56343, tzinfo=datetime.timezone.utc), verbose_name='lastLogin'),
        ),
        migrations.AlterField(
            model_name='moneynotesuser',
            name='password',
            field=models.CharField(max_length=1000, verbose_name='password'),
        ),
    ]
