# Generated by Django 4.2.3 on 2025-07-01 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_moneynotesuser_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneynotesuser',
            name='first_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='firstLogin'),
        ),
        migrations.AlterField(
            model_name='moneynotesuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='lastLogin'),
        ),
    ]
