# Generated by Django 4.2.3 on 2025-07-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_moneynotesuser_groups_moneynotesuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneynotesuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='moneynotesuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='moneynotesuser',
            name='user_permissions',
        ),
    ]
