# Generated by Django 4.2.3 on 2025-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_moneynotesuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneynotesuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moneynotesuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
