# Generated by Django 4.2.3 on 2025-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_moneynotesuser_is_active_moneynotesuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneynotesuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moneynotesuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
