# Generated by Django 4.2.3 on 2025-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_moneynotesuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneynotesuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='moneynotesuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='moneynotesuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
