# Generated by Django 4.2.3 on 2025-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_moneynotesuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneynotesuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moneynotesuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moneynotesuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
