# Generated by Django 4.2.3 on 2025-07-02 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_moneynotesuser_is_active_moneynotesuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('amount_type', models.CharField(choices=[('Income', 'Income'), ('Expenditure', 'Expenditure')], max_length=50, verbose_name='amountType')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notes_user_details', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notes_user_id', to='main.userid')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
