# Generated by Django 5.2.4 on 2025-07-11 04:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='firstName')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='lastName')),
                ('user_name', models.CharField(max_length=25, unique=True, verbose_name='userName')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email')),
                ('password', models.CharField(max_length=1000, verbose_name='password')),
                ('delete_date_time', models.DateTimeField(default=datetime.datetime(2025, 7, 11, 4, 36, 33, 491765, tzinfo=datetime.timezone.utc), verbose_name='deleteDateTime')),
            ],
        ),
    ]
