# Generated by Django 5.2.4 on 2025-07-11 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='delete_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 6, 44, 33, 226048, tzinfo=datetime.timezone.utc), verbose_name='deleteDateTime'),
        ),
    ]
