# Generated by Django 5.2.4 on 2025-07-11 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_emailverification_delete_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 6, 41, 39, 149685, tzinfo=datetime.timezone.utc), verbose_name='createdDateTime'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='delete_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 6, 46, 39, 149685, tzinfo=datetime.timezone.utc), verbose_name='deleteDateTime'),
        ),
    ]
