# Generated by Django 5.2.4 on 2025-07-11 06:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_emailverification_created_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='createdDateTime'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='delete_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 6, 48, 7, 154274, tzinfo=datetime.timezone.utc), verbose_name='deleteDateTime'),
        ),
    ]
