# Generated by Django 5.2.4 on 2025-07-11 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_emailverification_created_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='delete_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 7, 43, 44, 691426, tzinfo=datetime.timezone.utc), verbose_name='deleteDateTime'),
        ),
    ]
