# Generated by Django 5.2.4 on 2025-07-11 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_emailverification_delete_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='delete_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 10, 33, 27, 297503, tzinfo=datetime.timezone.utc), verbose_name='deleteDateTime'),
        ),
    ]
