# Generated by Django 5.2.4 on 2025-07-11 10:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_emailverification_delete_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='delete_date_time',
            field=models.DateTimeField(default=main.models.get_delete_time, verbose_name='deleteDateTime'),
        ),
    ]
