# Generated by Django 5.2.4 on 2025-07-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_emailverification_delete_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='isVerified'),
        ),
    ]
